#docker-compose -f --profile basic pull
#docker-compose -f --profile basic up

version: '3.3'
services:
  keycloak:
    image: "keycloak/keycloak:20.0.1"
    container_name: "keycloak"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgreskeycloak
      DB_DATABASE: ${KEYCLOAK_DATABASE_NAME}
      DB_USER: ${KEYCLOAK_DATABASE_USERNAME}
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8090:8080
#    networks:
#      - ypa
#    profiles:
#      - front&back
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"

  postgres:
    image: postgres:14.5-alpine3.16
    env_file:
      - .env
    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=!admin!
#      - POSTGRES_DB=admin
      #- PGDATA=/var/lib/postgresql/data/pgdata
      #- POSTGRES_DB=metastore
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M


  metastore:
    #image: hive-metastore:3.1.3
    build: ./metastore
    container_name: metastore
    ports:
      - "9083:9083"
    volumes:
      - ./metastore/metastore-site.xml:/usr/local/metastore/conf/metastore-site.xml:ro
    logging:
      options:
        max-size: "5MB"
        max-file: "5"
    depends_on:
        - postgres


  minio:
    image: minio/minio:RELEASE.2024-09-09T16-59-28Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  trino-coordinator:
    image: "trinodb/trino:457"
    ports:
      - '5542:5542'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
      - trino-coordinator-data:/data/trino
    depends_on:
      - metastore
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 3G

  trino-worker:
    image: "trinodb/trino:457"
    volumes:
      - ./trino/worker/etc:/etc/trino:ro
      - trino-worker-data:/data/trino
    depends_on:
      - metastore
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 6G

  superset:
    build: ./superset
    ports:
      - "8088:8088"
    volumes:
      - superset-data:/app/superset_home
    environment:
      - SUPERSET_SECRET_KEY=24865129682968Aa!
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local
  superset-data:
    driver: local
  trino-worker-data:
    driver: local
  trino-coordinator-data:
    driver: local
