CREATE USER hive WITH ENCRYPTED PASSWORD '!hive!';
CREATE DATABASE metastore;
GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;
GRANT ALL PRIVILEGES ON DATABASE metastore TO admin;
ALTER DATABASE metastore OWNER TO hive;